---
  - name: Install java
    yum:
      name: java-1.7.0-openjdk
      state: present

  - name: Download Subsonic RPM
    get_url:
      url: https://s3-eu-west-1.amazonaws.com/subsonic-public/download/subsonic-6.1.3.rpm
      dest: /root/subsonic-6.1.3.rpm

  - name: Install Subsonic rpm
    yum:
      name: /root/subsonic-6.1.3.rpm
      state: present
      disable_gpg_check: yes
